### ISSUE TITLE
Error: Cannot find module 'bluetooth-hci-socket'

### ISSUE THREAD

**Issue by xtools-at** [DigitalSecurity/mockle#1]
Hi guys,
I just wanted to try this out and installed it on my Pi Zero - I did everything from the bleno installs, but when I try to run mockle-create via CLI, it gives me
```
module.js:472
    throw err;
    ^

Error: Cannot find module 'bluetooth-hci-socket'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/mockle/node_modules/noble/lib/hci-socket/hci.js:6:26)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

```
I checked it,  ../noble/lib/hci-socket/hci.js is in the right location. reinstall of noble, bleno and bluetooth-bluetooth-hci-socket via npm did'nt help too...

Any help appreciated!

**Comment by xtools-at** [comment]
Never mind, figured it out - NPM install went wrong, I reinstalled all dependencies and bluetooth-hci-socket in /usr/local/lib/node_modules/mockle/node_modules/noble manually
